
import type { Card } from './types';

export const TAROT_DECK: Card[] = [
  // Major Arcana
  { id: 0, name: 'El Loco' },
  { id: 1, name: 'El Mago' },
  { id: 2, name: 'La Sacerdotisa' },
  { id: 3, name: 'La Emperatriz' },
  { id: 4, name: 'El Emperador' },
  { id: 5, name: 'El Hierofante' },
  { id: 6, name: 'Los Enamorados' },
  { id: 7, name: 'El Carro' },
  { id: 8, name: 'La Fuerza' },
  { id: 9, name: 'El Ermitaño' },
  { id: 10, name: 'La Rueda de la Fortuna' },
  { id: 11, name: 'La Justicia' },
  { id: 12, name: 'El Colgado' },
  { id: 13, name: 'La Muerte' },
  { id: 14, name: 'La Templanza' },
  { id: 15, name: 'El Diablo' },
  { id: 16, name: 'La Torre' },
  { id: 17, name: 'La Estrella' },
  { id: 18, name: 'La Luna' },
  { id: 19, name: 'El Sol' },
  { id: 20, name: 'El Juicio' },
  { id: 21, name: 'El Mundo' },
  // Wands (Bastos)
  { id: 22, name: 'As de Bastos' },
  { id: 23, name: 'Dos de Bastos' },
  { id: 24, name: 'Tres de Bastos' },
  { id: 25, name: 'Cuatro de Bastos' },
  { id: 26, name: 'Cinco de Bastos' },
  { id: 27, name: 'Seis de Bastos' },
  { id: 28, name: 'Siete de Bastos' },
  { id: 29, name: 'Ocho de Bastos' },
  { id: 30, name: 'Nueve de Bastos' },
  { id: 31, name: 'Diez de Bastos' },
  { id: 32, name: 'Sota de Bastos' },
  { id: 33, name: 'Caballo de Bastos' },
  { id: 34, name: 'Reina de Bastos' },
  { id: 35, name: 'Rey de Bastos' },
  // Cups (Copas)
  { id: 36, name: 'As de Copas' },
  { id: 37, name: 'Dos de Copas' },
  { id: 38, name: 'Tres de Copas' },
  { id: 39, name: 'Cuatro de Copas' },
  { id: 40, name: 'Cinco de Copas' },
  { id: 41, name: 'Seis de Copas' },
  { id: 42, name: 'Siete de Copas' },
  { id: 43, name: 'Ocho de Copas' },
  { id: 44, name: 'Nueve de Copas' },
  { id: 45, name: 'Diez de Copas' },
  { id: 46, name: 'Sota de Copas' },
  { id: 47, name: 'Caballo de Copas' },
  { id: 48, name: 'Reina de Copas' },
  { id: 49, name: 'Rey de Copas' },
  // Swords (Espadas)
  { id: 50, name: 'As de Espadas' },
  { id: 51, name: 'Dos de Espadas' },
  { id: 52, name: 'Tres de Espadas' },
  { id: 53, name: 'Cuatro de Espadas' },
  { id: 54, name: 'Cinco de Espadas' },
  { id: 55, name: 'Seis de Espadas' },
  { id: 56, name: 'Siete de Espadas' },
  { id: 57, name: 'Ocho de Espadas' },
  { id: 58, name: 'Nueve de Espadas' },
  { id: 59, name: 'Diez de Espadas' },
  { id: 60, name: 'Sota de Espadas' },
  { id: 61, name: 'Caballo de Espadas' },
  { id: 62, name: 'Reina de Espadas' },
  { id: 63, name: 'Rey de Espadas' },
  // Pentacles (Oros)
  { id: 64, name: 'As de Oros' },
  { id: 65, name: 'Dos de Oros' },
  { id: 66, name: 'Tres de Oros' },
  { id: 67, name: 'Cuatro de Oros' },
  { id: 68, name: 'Cinco de Oros' },
  { id: 69, name: 'Seis de Oros' },
  { id: 70, name: 'Siete de Oros' },
  { id: 71, name: 'Ocho de Oros' },
  { id: 72, name: 'Nueve de Oros' },
  { id: 73, name: 'Diez de Oros' },
  { id: 74, name: 'Sota de Oros' },
  { id: 75, name: 'Caballo de Oros' },
  { id: 76, name: 'Reina de Oros' },
  { id: 77, name: 'Rey de Oros' },
];

export const QUESTION_PROMPTS = [
    "Pasado / La base de la situación",
    "Presente / El desafío actual",
    "Futuro / El resultado potencial"
];
